In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('train.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
import sys
!{sys.executable} -m pip install  ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.34.0)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\hp\appdata\roaming\python\python311\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python311\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
%pip install pandas-profiling

Collecting pandas-profiling
  Downloading pandas_profiling-3.2.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Downloading joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (2.3.3)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (3.10.0)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (2.13.4)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (6.0.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (3.1.6)
Collecting markupsafe~=2.1.1 (from pandas-profiling)
  Downloading MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting visions==0.7.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Downloading visions-0.7.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.16.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (2.3.5)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting missingno>=0.4.2 (from pandas-profiling)
  Downloading missingno-0.5.2-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: phik>=0.11.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (0.12.5)
Collecting tangled-up-in-unicode==0.2.0 (from pandas-profiling)
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: requests>=2.24.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (2.34.0)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (4.67.3)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (0.13.2)
Requirement already satisfied: multimethod>=1.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas-profiling) (1.12)
Requirement already satisfied: attrs>=19.3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions==0.7.4->visions[type_image_path]==0.7.4->pandas-profiling) (3.6.1)
Requirement already satisfied: imagehash in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.2)
Requirement already satisfied: Pillow in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (12.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib>=3.2.0->pandas-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\hp\appdata\roaming\python\python311\site-packages (from pydantic>=1.8.1->pandas-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2026.4.22)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python311\site-packages (from tqdm>=4.48.2->pandas-profiling) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.17.0)
Requirement already satisfied: PyWavelets in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.9.0)
Downloading pandas_profiling-3.2.0-py2.py3-none-any.whl (262 kB)
   ---------------------------------------- 0.0/262.6 kB ? eta -:--:--
   -------------- ------------------------- 92.2/262.6 kB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 262.6/262.6 kB 3.2 MB/s eta 0:00:00
Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   --- ------------------------------------ 0.4/4.7 MB 11.6 MB/s eta 0:00:01
   ------ --------------------------------- 0.7/4.7 MB 9.5 MB/s eta 0:00:01
   ------------ --------------------------- 1.5/4.7 MB 10.7 MB/s eta 0:00:01
   ------------------- -------------------- 2.3/4.7 MB 13.5 MB/s eta 0:00:01
   ------------------------ --------------- 2.9/4.7 MB 12.3 MB/s eta 0:00:01
   ----------------------------- ---------- 3.5/4.7 MB 13.0 MB/s eta 0:00:01
   --------------------------------- ------ 4.0/4.7 MB 12.0 MB/s eta 0:00:01
   ------------------------------------- -- 4.4/4.7 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 4.7/4.7 MB 11.6 MB/s eta 0:00:00
Downloading visions-0.7.4-py3-none-any.whl (102 kB)
   ---------------------------------------- 0.0/102.4 kB ? eta -:--:--
   ---------------------------------------- 102.4/102.4 kB 6.1 MB/s eta 0:00:00
Downloading joblib-1.1.1-py2.py3-none-any.whl (309 kB)
   ---------------------------------------- 0.0/309.8 kB ? eta -:--:--
   ------------------- -------------------- 153.6/309.8 kB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 309.8/309.8 kB 3.8 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl (17 kB)
Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (pyproject.toml): started
  Building wheel for htmlmin (pyproject.toml): finished with status 'done'
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27172 sha256=4ded99ce5393908eff117a91736342713d579dbbc3159e477848107afec677e3
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\8d\55\1a\19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: htmlmin, tangled-up-in-unicode, markupsafe, joblib, visions, missingno, pandas-profiling
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.3
    Uninstalling MarkupSafe-3.0.3:
      Successfully uninstalled MarkupSafe-3.0.3
  Attempting uninstall: joblib
    Found existing installation: joblib 1.5.3
    Uninstalling joblib-1.5.3:
      Successfully uninstalled joblib-1.5.3
  Attempting uninstall: visions
    Found existing installation: visions 0.8.1
    Uninstalling visions-0.8.1:
      Successfully uninstalled visions-0.8.1
Successfully installed htmlmin-0.1.12 joblib-1.1.1 markupsafe-2.1.5 missingno-0.5.2 pandas-profiling-3.2.0 tangled-up-in-unicode-0.2.0 visions-0.7.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script htmlmin.exe is installed in 'c:\Users\HP\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pandas_profiling.exe is installed in 'c:\Users\HP\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.4 requires visions[type_image_path]<0.8.2,>=0.7.5, but you have visions 0.7.4 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import sys
!{sys.executable} -m pip install fg-data-profiling

Collecting fg-data-profiling
  Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Using cached visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (2.34.0)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from fg-data-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\hp\appdata\roaming\python\python311\site-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python311\site-packages (from tqdm<5,>=4.66.3->fg-data-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (1.30)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)
Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl (400 kB)
   ---------------------------------------- 0.0/400.3 kB ? eta -:--:--
   - ------------------------------------- 20.5/400.3 kB 640.0 kB/s eta 0:00:01
   --- ----------------------------------- 41.0/400.3 kB 653.6 kB/s eta 0:00:01
   --------------- ------------------------ 153.6/400.3 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 400.3/400.3 kB 3.1 MB/s eta 0:00:00
Using cached visions-0.8.1-py3-none-any.whl (105 kB)
Installing collected packages: visions, fg-data-profiling
  Attempting uninstall: visions
    Found existing installation: visions 0.7.4
    Uninstalling visions-0.7.4:
      Successfully uninstalled visions-0.7.4
Successfully installed fg-data-profiling-4.19.1 visions-0.8.1

  WARNING: The scripts data_profiling.exe and pandas_profiling.exe are installed in 'c:\Users\HP\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from data_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file(output_file='output.html')

100%|██████████| 12/12 [00:00<00:00, 34.32it/s]0<00:00,  7.17it/s, Describe variable: Embarked]
Summarize dataset: 100%|██████████| 47/47 [00:05<00:00,  8.91it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.16s/it]
Render HTML: 100%|██████████| 1/1 [00:04<00:00,  4.57s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 47.36it/s]

In [19]:
pf=pd.read_csv('test.csv')

In [15]:
rof = ProfileReport(pf)
rof.to_file(output_file='output.html')

100%|██████████| 15/15 [00:00<00:00, 264.43it/s]<00:00, 24.40it/s, Describe variable: Unnamed: 14]
Summarize dataset: 100%|██████████| 25/25 [00:01<00:00, 16.46it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.13s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 107.24it/s]

In [16]:
pf.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0